### ISSUE TITLE
Usage example with AWS Cognito temporary credentials

### ISSUE THREAD

**Issue by gnestor** [jimmyn/aws-mqtt-client#2]
> It is better to use AWS Cognito to provide temprerary credentiels for the front-end application...

Can you provide an example or link to one in the README? I've tried doing this myself but keeping getting `Unexpected response code: 403`. 

My steps:

1. Create a Federated Identity pool: https://console.aws.amazon.com/cognito/federated?region=us-east-1
2. Attach the `AWSIoTDataAccess` policy to that authenticated role of that pool
3. Add Facebook login to my front-end
4. Pass the Facebook token to the following:
```js
AWS.config.region = process.env.AWS_REGION
AWS.config = {
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: process.env.AWS_IDENTITY_POOL,
    Logins: {
      'graph.facebook.com': FACEBOOK_ACCESS_TOKEN
    }
  })
};
AWS.config.credentials.get(() => {
  const {accessKeyId, secretAccessKey, sessionToken} = AWS.config.credentials;
  this.mqttClient = new AWSMqtt({
    accessKeyId,
    secretAccessKey,
    sessionToken,
    endpointAddress: process.env.AWS_IOT_ENDPOINT_HOST,
    region: 'us-east-1'
  });
});
```

Thanks for your help!

**Comment by jimmyn** [comment]
@gnestor here is [Example from Amazon docs](http://docs.aws.amazon.com/cognito/latest/developerguide/facebook.html#using-facebook-1.javascript)

It seems that your code is fine. From which endpoint are you getting `403` responce.  Probably the problem is in AWS policies.

**Comment by gnestor** [comment]
Thanks @jimmyn. Ya, my code is consistent with Amazon's docs. Surprisingly, commenting out:

```js
Logins: {
  'graph.facebook.com': FACEBOOK_ACCESS_TOKEN
}
```

resolved it for me! This seems to imply that my unauthenticated role has the proper policies for IoT and my authenticated role doesn't, but I attached the `AWSIoTDataAccess` policy to both... Any other thoughts?

**Comment by jimmyn** [comment]
Check this answer - http://stackoverflow.com/a/40305905/5444431. I don't use cognito in my projects so I can't tell whether it works or not.

**Comment by gnestor** [comment]
@jimmyn You da man! That was extremely helpful! Who would've known that you needed to call an additional `AttachPrincipalPolicy`? I provided a follow up answer with my implementation: http://stackoverflow.com/a/41596213/2217533

**Comment by lakshmantgld** [comment]
@jimmyn I am not using cognito. What should be the **session_token** ? I am getting the 403 error like this: **Websocket connection to <wss://URL>  failed. Error during WebSocket handshake: Unexpected response code: 403**.

**Comment by jimmyn** [comment]
@lakshmantgld `sessionToken` is optional and used only when you have temporary credentials. Check your policy attached to your credentials. Maybe you don't have access.

**Comment by lakshmantgld** [comment]
Removing the sessionToken worked!!
