### ISSUE TITLE
AWSMqtt is not a constructor/function

### ISSUE THREAD

**Issue by 0xearl** [jimmyn/aws-mqtt-client#7]
whenever i try to create a new AWSMqtt, i get this error saying its not a constructor nor a function but when i try to console log the AWSMqtt its result is { default: [Function: AWSMqtt] }

node version: 14.17.0
![image](https://user-images.githubusercontent.com/58910880/133627666-a733e257-da50-4f27-8e48-3af9100602ac.png)

**Comment by AlanKev117** [comment]
Did you find a solution for this, @0xearl?

**Comment by 0xearl** [comment]
@AlanKev117 , sorry for the very late reply here. nope i haven't. i have decided to use https://aws-amplify.github.io/amplify-js/api/classes/awsiotprovider.html
